### ISSUE TITLE
Vulkan Rendering for Bevy Oxr

### ISSUE THREAD

**Issue by MiniMinerX** [mosure/bevy_gaussian_splatting#117]
I am trying to get Bevy oxr to work with bgs and I am very close. When I run using d3d12 in bev_mod_openxr, i can get the gaussians to show up just fine. However, when i compile native to the quest and vulkan is used, the splats are nowhere to be seen. The app doesnt crash, passthrough and all other bevy assets work. I believe the issue stems from vulkan not working properly for the splats. I brought this issue here. Is there somewhere I can start to make sure vulkan works too? Once this is working we can mark the openxr feature on its way to completion for native quest. Thanks for the help again, I'll add to the examples sections soon for this.

**Comment by mosure** [comment]
a minimal example would be great!

since it does work with d3d12 + bevy_mod_openxr (and vulkan + vanilla bevy), it seems to indicate an issue with the bevy_mod_openxr vulkan backend, maybe handling transparent phase items or indirect drawing incorrectly.

XR gaussian splatting is exciting work 🚀

**Comment by MiniMinerX** [comment]
thanks for the tip!

**Comment by MiniMinerX** [comment]
I have a new idea. I have the embedded assets plugin in my rust app, but I don't think the shades are being embedded into the binary in bgs. I think the shades may not be being sent over. I also found some debug lines noting Vulkan is missing features so I'll try to add those in too.

**Comment by MiniMinerX** [comment]
The issue was not with BGS or bevy_mod_xr, it was with x build. i had my splat file inside of assets/scenes/my_splat.gcloud. However, x build has a bug where any file in the assets/ root is sent over, but the subfolders like assets/scenes were not. I dumped my splat into the root assets/my_splat.gcloud and it worked like a charm. My small splats are really smooth in vr, letting me move them with my hand. The larger splats are laggier, but when i shrink the large splat to the size of my hand its smooth, i dont know why that is. But its cool! I'll make an example soon

**Comment by mosure** [comment]
when running on quest, a tile gaussian render pipeline would be more efficient. I'll open a feature issue for it.
