### ISSUE TITLE
Multi Cam still breaking

### ISSUE THREAD

**Issue by MiniMinerX** [mosure/bevy_gaussian_splatting#120]
I have this error: Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(1564, 1, Vulkan)>`
    In a set_bind_group command
      note: bind group = `render_sorted_bind_group`
    Dynamic binding index 0 (targeting bind group 3, binding 0) with value 260944, does not respect device's requested `min_storage_buffer_offset_alignment` limit: 32 and i keep getting it with these two cameras:

commands.spawn((
        GaussianCamera,
        Camera3dBundle {
            camera: Camera {
                order: 2,
                target: RenderTarget::TextureView(ManualTextureViewHandle(100)),
                ..default()
            },
            transform: Transform::from_translation(Vec3::new(0.0, 1.0, 1.0)),
            tonemapping: Tonemapping::None,
            ..default()
        },

    ));

    #[cfg(feature = "pc")] 
    commands.spawn((
        Camera3dBundle {
            camera: Camera{
                order: 1,
                ..default()
            },
            ..default()
        },
        PanOrbitCamera::default(),
        GaussianCamera,

        //bevy_transform_gizmo::GizmoPickSource::default(),
    ));

**Comment by MiniMinerX** [comment]
Updates on this issue: I kind of got multi cam working again. It looks like i have to spawn my splats before i spawn the cameras. If i do that then the splat loads fine. I'm going to try a quick fix function that on loading a new splat, removed guassian camera from all the cams, spawns the splat, and gives the GaussianCamera component back to each camera just for now.  Its a boof solution but may work.

**Comment by mosure** [comment]
I've implemented a similar 'camera warmup' concept in #121 until the underlying problem can be resolved. it looks like the extracted view uniform offset 

the original error is caused by a padding requirement, this line should address that: https://github.com/mosure/bevy_gaussian_splatting/pull/121/files#diff-77bdd0709026ed95e28dd56102ea789e4825860afa7f3e6da3786504e072b49aR103
