### ISSUE TITLE
How to reference an example from another repo in bgs

### ISSUE THREAD

**Issue by MiniMinerX** [mosure/bevy_gaussian_splatting#127]
I created an example for using bgs with bevy_mod_oxr 

https://github.com/MiniMinerX/bevy_gaussian_oxr_simple

How should I add this example into this repo, since it would be useful to reference for the oxr support.

**Comment by MiniMinerX** [comment]
https://github.com/MiniMinerX/bevy_gaussian_oxr_simple

**Comment by mosure** [comment]
awesome oxr example!

seeing xr as a platform, similar to wasm, to port as an example here, any xr-specific dependencies would need to be available from crates.io and optional with an xr cargo feature.

minimal xr-specific systems (e.g. camera controls) can be added to the existing viewer, e.g. https://github.com/mosure/bevy_gaussian_splatting/blob/b8d7ed106b8c5049a93bbfd63fe593ce4f82c16f/viewer/viewer.rs#L138

this would allow running on an xr example directly, e.g. `cargo run --bin viewer --features xr`


also feel free to start a discussion linking your project.
