### ISSUE TITLE
Precompute Covariance Loading Issues

### ISSUE THREAD

**Issue by MiniMinerX** [mosure/bevy_gaussian_splatting#128]
Im trying to use the following subset of features: 

bevy_gaussian_splatting = { version = "2.7.5", default-features = false, features = ["buffer_storage", "planar", "f16", "io_ply", "io_flexbuffers", "sort_rayon", "sh0", "precompute_covariance_3d"] }

and when I load either a .ply or .gcloud, the file fails to load and it crashes due to this section .

I tried to convert the ply to gcloud in two ways, one with and one without precompute covariance feature enables. When i tried to load the precomputed covariance gcloud with the feature turned on i got this thread 'IO Task Pool (0)' panicked at ... bevy_gaussian_splatting-2.7.5\src\io\gcloud\flexbuffers.rs:26:56: 
deserialization failed: Serde("missing field `covariance_3d_opacity_packed128`")
and when i tried to load the ply this happened: 

E event ... bevy_render-0.14.2\serror: no definition in scope for identifier: 'get_rotation'
...
let rotation = get_rotation(index);
^^^^^^^^^^^^ unknown identifier

but no crash

and when i tried to load the normal gcloud made normally without the precompute feature. Note i still have the precompute covariance feature enabled for my viewer, but the gcloud is just genreated normally unlike before: i get this error:  Abort message: 'deserialization failed: Serde("missing field `covariance_3d_opacity_packed128`")' with a crash. Soooo it seems in the last two cases, serde is looking for the covariance_3d_opacity_packed128 which is needed for the precomputed feature. So when i generated a gcloud with the feature enabled and started the viewer with the feature enabled i got this :  Abort message: 'deserialization failed: Serde("missing field `covariance_3d_opacity_packed128`")', so the plys just dont have that form right now and the gcloud is not being saved with the data i think. Sorry if this is confusing. Also in each case a camera had to exist or it would crash too (but thats ok).

**Comment by mosure** [comment]
the expected flow would be:
- convert ply to gcloud
    - `cargo run --bin ply_to_gcloud --no-default-features --features="tooling buffer_storage planar f16 io_ply io_flexbuffers sort_rayon sh0 precompute_covariance_3d" -- {path_to_ply}`

- load the gcloud into the viewer using the same features
    - `cargo run --no-default-features --features="tooling buffer_storage planar f16 io_ply io_flexbuffers sort_rayon sh0 precompute_covariance_3d" -- --input-file {path_to_gcloud}`

the linked PR #129 resolves the shader conflict between precomp_cov3 and surfels.
